services:

  app-prod:
    image: gcsoft-app:prod
    container_name: gcsoft_prod_app
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      APP_ENV: production
      DB_HOST: mysql-shared
      DB_PORT: 3306
      DB_NAME: gcsoft_prod
      DB_USER: gcsoft
      DB_PASS: gcsoft123
    networks:
      - gcsoft-net

networks:
  gcsoft-net:
    external: true
    name: gcsoft-net
